# Generated by Django 4.2.16 on 2026-05-10 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('equation_type', models.CharField(choices=[('linear', 'Linear'), ('quadratic', 'Quadratic'), ('cubic', 'Cubic'), ('trigonometric', 'Trigonometric'), ('derivative', 'Derivative'), ('integral', 'Integral'), ('geometry', 'Geometry'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('expression', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('equation_type', models.CharField(blank=True, max_length=20)),
                ('expression', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=50)),
                ('min_value', models.FloatField(default=-10.0)),
                ('max_value', models.FloatField(default=10.0)),
                ('default_value', models.FloatField(default=1.0)),
                ('step', models.FloatField(default=0.1)),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='visualizer.equation')),
            ],
        ),
    ]
